sudo: required

services:
  - docker

before_install:
  - docker build -t lexyblazy/docker-react -f DockerFile.dev .

scripts:
  - docker run lexyblazy/docker-react npm run test:ci

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-017908065641"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_EBS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_EBS_SECRET_KEY"
