version: 2.1

defaults: &defaults
  working_directory: /app
  docker:
    - image: docker:17.05.0-ce-git

common-test: &common-test
  steps:
    - checkout
    - setup_remote_docker
    - run: docker build -t app -f DockerFile.dev .
    - run: docker run app npm run test:ci

common-deploy: &common-deploy
  steps:
    # - checkout
    - run: echo "We will soon be deploying"

jobs:
  test:
    <<: *defaults
    <<: *common-test
  deploy:
    <<: *defaults
    <<: *common-deploy
workflows:
  version: 2
  main:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - test