version: 2.1

defaults: &defaults
  working_directory: /app
  docker:
    - image: docker:17.05.0-ce-git

# aliases:
#   - &common-test:
#     steps:
#       - checkout
#       - setup_remote_docker
#       - run: docker build -t app -f DockerFile.dev .
#       - run: docker run app npm run test:ci

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t app -f DockerFile.dev .
      - run:
          name: Run Tests
          command: |
            docker run app npm run test:ci

workflows:
  version: 2
  main:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
