version: 2.1

# defaults: &defaults
#   working_directory: /app
#   docker:
#     - image: docker:17.05.0-ce-git


aliases:
  - &common-test:
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t app -f DockerFile.dev .
      - run: docker run app npm run test:ci


jobs:
  test:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    <<: *common-test

workflows:
  version: 2
  main:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
